import { jsPDF } from 'jspdf';
import { saveAs } from 'file-saver';

/**
 * Download lyrics as LRC file (synced lyrics format)
 */
export function downloadAsLRC(song) {
  const lyrics = song.syncedLyrics || convertPlainToLRC(song.plainLyrics);
  if (!lyrics) throw new Error('No lyrics available');

  const header = [
    `[ti:${song.title}]`,
    `[ar:${song.artist}]`,
    `[al:${song.album || 'Unknown'}]`,
    song.duration ? `[length:${formatTime(song.duration)}]` : '',
    `[by:SpoLyPDF]`,
    '',
  ].filter(Boolean).join('\n');

  const content = header + '\n' + lyrics;
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `${sanitizeFilename(song.artist)} - ${sanitizeFilename(song.title)}.lrc`);
}

/**
 * Download lyrics as plain TXT file
 */
export function downloadAsTXT(song) {
  const lyrics = song.plainLyrics || stripLRCTimestamps(song.syncedLyrics);
  if (!lyrics) throw new Error('No lyrics available');

  const header = `${song.title}\nby ${song.artist}\n${song.album ? `Album: ${song.album}` : ''}\n${'─'.repeat(40)}\n\n`;
  const content = header + lyrics;
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `${sanitizeFilename(song.artist)} - ${sanitizeFilename(song.title)}.txt`);
}

/**
 * Download lyrics as PDF
 */
export function downloadAsPDF(song) {
  const lyrics = song.plainLyrics || stripLRCTimestamps(song.syncedLyrics);
  if (!lyrics) throw new Error('No lyrics available');

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Background
  doc.setFillColor(15, 15, 15);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Accent bar at top
  doc.setFillColor(29, 185, 84);
  doc.rect(0, 0, pageWidth, 3, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  y += 5;
  doc.text(song.title, margin, y);
  y += 10;

  // Artist
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(29, 185, 84);
  doc.text(`by ${song.artist}`, margin, y);
  y += 7;

  // Album
  if (song.album) {
    doc.setFontSize(11);
    doc.setTextColor(150, 150, 150);
    doc.text(`Album: ${song.album}`, margin, y);
    y += 5;
  }

  // Divider
  y += 5;
  doc.setDrawColor(50, 50, 50);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Lyrics
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(220, 220, 220);

  const lines = lyrics.split('\n');
  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      doc.setFillColor(15, 15, 15);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      y = margin;
    }

    if (line.trim() === '') {
      y += 4;
    } else {
      const splitLines = doc.splitTextToSize(line, maxWidth);
      for (const sl of splitLines) {
        if (y > pageHeight - margin) {
          doc.addPage();
          doc.setFillColor(15, 15, 15);
          doc.rect(0, 0, pageWidth, pageHeight, 'F');
          y = margin;
        }
        doc.text(sl, margin, y);
        y += 6;
      }
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.text('Generated by SpoLyPDF', margin, pageHeight - 10);

  doc.save(`${sanitizeFilename(song.artist)} - ${sanitizeFilename(song.title)}.pdf`);
}

/**
 * Download lyrics as SRT subtitle format
 */
export function downloadAsSRT(song) {
  const synced = song.syncedLyrics;
  if (!synced) {
    // Fallback: create SRT from plain lyrics with approximate timing
    const plain = song.plainLyrics;
    if (!plain) throw new Error('No lyrics available');
    
    const lines = plain.split('\n').filter(l => l.trim());
    const duration = song.duration || lines.length * 3;
    const interval = duration / lines.length;
    
    let srt = '';
    lines.forEach((line, i) => {
      const start = formatSRTTime(i * interval);
      const end = formatSRTTime((i + 1) * interval);
      srt += `${i + 1}\n${start} --> ${end}\n${line}\n\n`;
    });
    
    const blob = new Blob([srt], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `${sanitizeFilename(song.artist)} - ${sanitizeFilename(song.title)}.srt`);
    return;
  }

  // Parse LRC timestamps and convert to SRT
  const lrcLines = synced.split('\n').filter(l => l.trim());
  let srt = '';
  let counter = 1;

  for (let i = 0; i < lrcLines.length; i++) {
    const match = lrcLines[i].match(/\[(\d+):(\d+\.?\d*)\]\s*(.*)/);
    if (!match) continue;

    const startSecs = parseInt(match[1]) * 60 + parseFloat(match[2]);
    let endSecs;

    // Find next timestamp for end time
    if (i + 1 < lrcLines.length) {
      const nextMatch = lrcLines[i + 1].match(/\[(\d+):(\d+\.?\d*)\]/);
      if (nextMatch) {
        endSecs = parseInt(nextMatch[1]) * 60 + parseFloat(nextMatch[2]);
      }
    }
    if (!endSecs) endSecs = startSecs + 3;

    const text = match[3].trim();
    if (!text) continue;

    srt += `${counter}\n${formatSRTTime(startSecs)} --> ${formatSRTTime(endSecs)}\n${text}\n\n`;
    counter++;
  }

  const blob = new Blob([srt], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `${sanitizeFilename(song.artist)} - ${sanitizeFilename(song.title)}.srt`);
}

/**
 * Download all songs' lyrics as a single PDF
 */
export function downloadAllAsPDF(songs) {
  const validSongs = songs.filter(s => s.plainLyrics || s.syncedLyrics);
  if (validSongs.length === 0) throw new Error('No lyrics available');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  validSongs.forEach((song, songIndex) => {
    if (songIndex > 0) doc.addPage();

    // Background
    doc.setFillColor(15, 15, 15);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    // Accent bar
    doc.setFillColor(29, 185, 84);
    doc.rect(0, 0, pageWidth, 3, 'F');

    let y = margin + 5;

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text(song.title, margin, y);
    y += 10;

    // Artist
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(29, 185, 84);
    doc.text(`by ${song.artist}`, margin, y);
    y += 7;

    if (song.album) {
      doc.setFontSize(11);
      doc.setTextColor(150, 150, 150);
      doc.text(`Album: ${song.album}`, margin, y);
      y += 5;
    }

    y += 5;
    doc.setDrawColor(50, 50, 50);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    const lyrics = song.plainLyrics || stripLRCTimestamps(song.syncedLyrics);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(220, 220, 220);

    const lines = lyrics.split('\n');
    for (const line of lines) {
      if (y > pageHeight - margin) {
        doc.addPage();
        doc.setFillColor(15, 15, 15);
        doc.rect(0, 0, pageWidth, pageHeight, 'F');
        y = margin;
      }
      if (line.trim() === '') {
        y += 4;
      } else {
        const splitLines = doc.splitTextToSize(line, maxWidth);
        for (const sl of splitLines) {
          if (y > pageHeight - margin) {
            doc.addPage();
            doc.setFillColor(15, 15, 15);
            doc.rect(0, 0, pageWidth, pageHeight, 'F');
            y = margin;
          }
          doc.text(sl, margin, y);
          y += 6;
        }
      }
    }

    // Page number
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`${songIndex + 1} / ${validSongs.length}  •  SpoLyPDF`, margin, pageHeight - 10);
  });

  doc.save('SpoLyPDF_Lyrics_Collection.pdf');
}

// ── Helpers ──

function sanitizeFilename(name) {
  return (name || 'unknown').replace(/[<>:"/\\|?*]/g, '_').substring(0, 100);
}

function formatTime(seconds) {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

function formatSRTTime(totalSeconds) {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = Math.floor(totalSeconds % 60);
  const ms = Math.floor((totalSeconds % 1) * 1000);
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')},${ms.toString().padStart(3, '0')}`;
}

function stripLRCTimestamps(lrc) {
  if (!lrc) return '';
  return lrc.replace(/\[\d+:\d+\.?\d*\]\s*/g, '');
}

function convertPlainToLRC(plain) {
  if (!plain) return null;
  // Simple conversion: no timestamps, just lyrics lines
  return plain.split('\n').map(line => `[00:00.00] ${line}`).join('\n');
}
